// <auto-generated />
namespace Apparent.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddTBL_APPARENT_SERVICE_PAYMENT : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTBL_APPARENT_SERVICE_PAYMENT));
        
        string IMigrationMetadata.Id
        {
            get { return "202403281051370_AddTBL_APPARENT_SERVICE_PAYMENT"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
